name: freeze
main: Bavfalcon9\freeze\Main
version: 2.2.1
api: [5.0.0]
load: POSTWORLD
authors: [Bavfalcon9, fernanACM, 0x00032]
description: Freeze for PocketMine-MP 5.0

commands:
  frozen:
    description: See a list of frozen users.
    permission: freeze.command
  freeze:
    description: Freeze a player
    permission: freeze.command
  unfreeze:
    description: Unfreeze a player
    permission: freeze.command
  thaw:
    description: Unfreeze a player
    permission: freeze.command
permissions:
  freeze:
    description: All permissions for freeze
    default: op
  freeze.immune:
    description: Makes yourself immune to /freeze
    default: op
  freeze.command:
    description: Allows yourself to freeze players
    default: op
