name: freeze
main: bavfalcon9\Main
version: 2.0.0
api: [3.0.0, 3.5.1, 3.5.0, 3.6.0, 3.6.4]
load: POSTWORLD
author: Bavfalcon9
description: Freeze
commands:
  frozen:
    description: See a list of frozen users.
  freeze:
    description: Freeze a player
  unfreeze:
    description: Unfreeze a player
  thaw:
    description: Unfreeze a player
permissions:
    freeze:
      description: All permissions for freeze
      default: op
    freeze.immune:
      description: Makes yourself immune to /freeze
      default: op
    freeze.command:
      description: Allows yourself to freeze players
      default: op